# Main Parameters
title: Basic Performix Report
subtitle: A minimal example show casing features
author: Biometix
date: 5th March 2020
keywords: '[analytics]'
# Personal Params
contact: Ted Dunstone
contact_phone: +61 (2) 419990968
contact_email: ted@biometix.com
classification: Commercial in Confidential
# Report Specific Params

news: covid id border
query: corona virus

