# Main Parameters
title: Covid-19 Impact Report New
subtitle: Estimates of Covid-19 Impact for Singapore
author: Biometix
date: 5th March 2020
keywords: '[biometrics]'
# Personal Params
contact: Ted Dunstone
contact_phone: +61 (2) 419990968
contact_email: ted@biometix.com
classification: Commercial in Confidential
# Report Specific Params

news: covid id border
query: corona virus

