# Main Parameters
title: Biometric Analysis
subtitle: Analysis of data for AFIS fingerprint matcher
author: Biometix
date: 15th April 2020
keywords: "[biometrics]"
# Personal Params
contact: Edward Kopka
contact_phone: 0490057270
contact_email: e.kopka@biometix.com
# Report Specific Params
results_file: raw_results/scores_matches.csv
analysis_file: raw_results/raw_results.json
