# Main Parameters
title: Enrollment Issues Simprint
subtitle:  Design and Usage Information for Techncial Users
author: Biometix
date: 5th March 2020
keywords: '[analytics]'
# Personal Params
contact: Ted Dunstone
contact_phone: +61 (2) 419990968
contact_email: ted@biometix.com
classification: Commercial in Confidential
# Report Specific Params

customer: Biometix
query: 123

